// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1FDuv0a4gsoag1pSbNaLmJon3XPdvNF8',
    appId: '1:174308292710:web:0d09f66d21a2955e1995a7',
    messagingSenderId: '174308292710',
    projectId: 'my-new-project-6b3b3',
    authDomain: 'my-new-project-6b3b3.firebaseapp.com',
    storageBucket: 'my-new-project-6b3b3.appspot.com',
    measurementId: 'G-6955VQE9P5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtGs8nYm0ZEnRDKKE5VLyjanEfKy5mYmI',
    appId: '1:174308292710:android:b13dd3ce8e1be06b1995a7',
    messagingSenderId: '174308292710',
    projectId: 'my-new-project-6b3b3',
    storageBucket: 'my-new-project-6b3b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0jNvXfgc3QM-EbPYRhCBIWVuWEu6-4co',
    appId: '1:174308292710:ios:26d8a33a9833d8171995a7',
    messagingSenderId: '174308292710',
    projectId: 'my-new-project-6b3b3',
    storageBucket: 'my-new-project-6b3b3.appspot.com',
    iosBundleId: 'com.example.firebaseLoginRegistation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1FDuv0a4gsoag1pSbNaLmJon3XPdvNF8',
    appId: '1:174308292710:web:19b1b9c50a26f64a1995a7',
    messagingSenderId: '174308292710',
    projectId: 'my-new-project-6b3b3',
    authDomain: 'my-new-project-6b3b3.firebaseapp.com',
    storageBucket: 'my-new-project-6b3b3.appspot.com',
    measurementId: 'G-EX97EMKQ6R',
  );
}
